spring.application.name=RESUME-SECTION-SERVICE


server.port=8084

spring.mongodb.uri=mongodb+srv://vishwajeetsingh4888:Vishu%40md123@resumebuilder.3qfuosl.mongodb.net/resumebuilder?appName=resumebuilder

# ===============================
# DATABASE CONFIG (MySQL / AWS RDS)
# ===============================
#spring.datasource.url=jdbc:mysql://localhost:3306/resume_builder
#spring.datasource.username=root
#spring.datasource.password=Vishu@sql123
#
## ===============================
## JPA / HIBERNATE CONFIG
## ===============================
#spring.jpa.hibernate.ddl-auto=update